name: CI
on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2
          args: --config=.golangci.yml
      - name: Install revive
        run: go install github.com/mgechev/revive@v1.1.3
      - name: Run revive
        run: revive -set_exit_status=1
      - name: Run Unit tests
        run: go test
      - name: Check go mod tidyness
        run: ./tools/check-go-mod.sh
